### ISSUE TITLE
Game Crashing

### ISSUE THREAD

**Issue by m0thknight** [LieOnLion/Quad#3]
game won't open, instantly crashes.

[22Feb2024 12:16:37.771] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, m0thknight, --version, 1.20.1, --gameDir, C:\Users\kitte\AppData\Roaming\com.modrinth.theseus\profiles\Valen1.20, --assetsDir, C:\Users\kitte\AppData\Roaming\com.modrinth.theseus\meta\assets, --assetIndex, 5, --uuid, 07e41fa9646b468cb5280d86bd007dcc, --accessToken, ????????, --clientId, c4502edb-87c6-40cb-b595-64a280cf8906, --xuid, 0, --userType, msa, --versionType, release, --width, 854, --height, 480, --launchTarget, forgeclient, --fml.forgeVersion, 47.2.17, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412]
[22Feb2024 12:16:37.775] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.9 by Azul Systems, Inc.; OS Windows 10 arch amd64 version 10.0
[22Feb2024 12:16:39.022] [main/INFO] [net.minecraftforge.fml.loading.ImmediateWindowHandler/]: Loading ImmediateWindowProvider fmlearlywindow
[22Feb2024 12:16:39.076] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.6
[22Feb2024 12:16:39.155] [main/INFO] [EARLYDISPLAY/]: Requested GL version 4.6 got version 4.6
[22Feb2024 12:16:39.225] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/kitte/AppData/Roaming/com.modrinth.theseus/meta/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%23121!/ Service=ModLauncher Env=CLIENT
[22Feb2024 12:16:39.260] [pool-2-thread-1/INFO] [EARLYDISPLAY/]: GL info: AMD Radeon RX 6600 XT GL version 4.6.0 Core Profile Context 23.9.1.230821, ATI Technologies Inc.
[22Feb2024 12:16:40.228] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\kitte\AppData\Roaming\com.modrinth.theseus\meta\libraries\net\minecraftforge\fmlcore\1.20.1-47.2.17\fmlcore-1.20.1-47.2.17.jar is missing mods.toml file
[22Feb2024 12:16:40.231] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\kitte\AppData\Roaming\com.modrinth.theseus\meta\libraries\net\minecraftforge\javafmllanguage\1.20.1-47.2.17\javafmllanguage-1.20.1-47.2.17.jar is missing mods.toml file
[22Feb2024 12:16:40.233] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\kitte\AppData\Roaming\com.modrinth.theseus\meta\libraries\net\minecraftforge\lowcodelanguage\1.20.1-47.2.17\lowcodelanguage-1.20.1-47.2.17.jar is missing mods.toml file
[22Feb2024 12:16:40.235] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\kitte\AppData\Roaming\com.modrinth.theseus\meta\libraries\net\minecraftforge\mclanguage\1.20.1-47.2.17\mclanguage-1.20.1-47.2.17.jar is missing mods.toml file
[22Feb2024 12:16:40.494] [main/WARN] [net.minecraftforge.jarjar.selection.JarSelector/]: Attempted to select two dependency jars from JarJar which have the same identification: Mod File:  and Mod File: . Using Mod File: 
[22Feb2024 12:16:40.495] [main/WARN] [net.minecraftforge.jarjar.selection.JarSelector/]: Attempted to select a dependency jar for JarJar which was passed in as source: terrablender. Using Mod File: C:\Users\kitte\AppData\Roaming\com.modrinth.theseus\profiles\Valen1.20\mods\TerraBlender-forge-1.20.1-3.0.1.4.jar
[22Feb2024 12:16:40.495] [main/WARN] [net.minecraftforge.jarjar.selection.JarSelector/]: Attempted to select a dependency jar for JarJar which was passed in as source: resourcefullib. Using Mod File: C:\Users\kitte\AppData\Roaming\com.modrinth.theseus\profiles\Valen1.20\mods\resourcefullib-forge-1.20.1-2.1.23.jar
[22Feb2024 12:16:40.495] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator/]: Found 17 dependencies adding them to mods collection
[22Feb2024 12:16:43.103] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[22Feb2024 12:16:43.259] [main/ERROR] [mixin/]: Mixin config rei-jei-internals-workaround.mixins.json does not specify "minVersion" property
[22Feb2024 12:16:43.264] [main/ERROR] [mixin/]: Mixin config lolmcv.mixins.json does not specify "minVersion" property
[22Feb2024 12:16:43.274] [main/ERROR] [mixin/]: Mixin config lolenderite.mixins.json does not specify "minVersion" property
[22Feb2024 12:16:43.306] [main/ERROR] [mixin/]: Mixin config quad.mixins.json does not specify "minVersion" property
[22Feb2024 12:16:43.337] [main/ERROR] [mixin/]: Mixin config azurelib.mixins.json does not specify "minVersion" property
[22Feb2024 12:16:43.338] [main/ERROR] [mixin/]: Mixin config azurelib.forge.mixins.json does not specify "minVersion" property
[22Feb2024 12:16:43.430] [main/ERROR] [mixin/]: Mixin config rei.mixins.json does not specify "minVersion" property
[22Feb2024 12:16:43.467] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.20.1, --gameDir, C:\Users\kitte\AppData\Roaming\com.modrinth.theseus\profiles\Valen1.20, --assetsDir, C:\Users\kitte\AppData\Roaming\com.modrinth.theseus\meta\assets, --uuid, 07e41fa9646b468cb5280d86bd007dcc, --username, m0thknight, --assetIndex, 5, --accessToken, ????????, --clientId, c4502edb-87c6-40cb-b595-64a280cf8906, --xuid, 0, --userType, msa, --versionType, release, --width, 854, --height, 480]
[22Feb2024 12:16:43.491] [main/WARN] [mixin/]: Reference map 'labels-common-refmap.json' for labels-common.mixins.json could not be read. If this is a development environment you can ignore this message
[22Feb2024 12:16:43.492] [main/WARN] [mixin/]: Reference map 'labels-forge-refmap.json' for labels.mixins.json could not be read. If this is a development environment you can ignore this message
[22Feb2024 12:16:43.498] [main/WARN] [mixin/]: Reference map 'spelunkery-forge-refmap.json' for spelunkery.mixins.json could not be read. If this is a development environment you can ignore this message
[22Feb2024 12:16:43.518] [main/INFO] [Embeddium/]: Loaded configuration file for Embeddium: 278 options available, 3 override(s) found
[22Feb2024 12:16:43.519] [main/INFO] [Embeddium-GraphicsAdapterProbe/]: Searching for graphics cards...
[22Feb2024 12:16:43.690] [main/INFO] [Embeddium-GraphicsAdapterProbe/]: Found graphics card: GraphicsAdapterInfo[vendor=AMD, name=AMD Radeon RX 6600 XT, version=DriverVersion=31.0.21031.1005]
[22Feb2024 12:16:43.746] [main/WARN] [mixin/]: Reference map 'experienced_crops-forge-refmap.json' for experienced_crops.mixins.json could not be read. If this is a development environment you can ignore this message
[22Feb2024 12:16:43.832] [main/WARN] [mixin/]: Reference map 'idas.refmap.json' for idas.mixins.json could not be read. If this is a development environment you can ignore this message
[22Feb2024 12:16:43.859] [main/WARN] [mixin/]: Reference map '${refmap_target}refmap.json' for corgilib.forge.mixins.json could not be read. If this is a development environment you can ignore this message
[22Feb2024 12:16:43.914] [main/INFO] [Puzzles Lib/]: Loading 234 mods:
	- advancementplaques 1.5.1
	- alexscaves 1.1.1
	- alexsdelight 1.5
	- alexsmobs 1.22.7
	- all_bark_all_bite 1.20.1-1.0.2
	- another_furniture 1.20.1-3.0.1
	- appleskin 2.5.1+mc1.20.1
	- archaeologybanners 5.1.4
	- architectury 9.1.13
	- armortrimitemfix 1.0.2
	- athena 3.1.1
	- azurelib 2.0.20
	- babyfat 1.0.0
	- backpacked 2.2.5
	- bagus_lib 1.20.1-4.3.0
	- bbs 1.20.1-0.1.3
	- bee_info 1.1.2
	- betterarcheology 1.1.6-1.20.1
	- betterdeserttemples 1.20-Forge-3.0.3
	- betterdungeons 1.20-Forge-4.0.3
	- betterendisland 1.20-Forge-2.0.5
	- betterf3 7.0.2
	- betterfortresses 1.20-Forge-2.0.5
	- betterjungletemples 1.20-Forge-2.0.4
	- betterlily 1.20-1.3.1
	- bettermineshafts 1.20-Forge-4.0.4
	- betteroceanmonuments 1.20-Forge-3.0.4
	- betterstrongholds 1.20-Forge-4.0.3
	- betterwitchhuts 1.20-Forge-3.0.3
	- biomemakeover 1.20.1-1.11.4
	- blockrunner 8.0.3
	- blueprint 7.0.0
	- bonezone 3.0.3
	- bookshelf 20.1.9
	- bountiful 6.0.3+1.20.1
	- brutes_dropscraps_mr 1.1
	- caelus 3.1.0+1.20
	- carryon 2.1.2.7
	- cavesanddepths 1.2.3
	- charmofundying 6.4.5+1.20.1
	- chefsdelight 1.0.3-forge-1.20.1
	- citadel 2.5.3
	- cleardespawn 1.1.15
	- cloth_config 11.1.118
	- clumps 12.0.0.3
	- collective 7.32
	- colorize 1.9.0
	- commonnetworking 1.0.2-1.20.1
	- companion 5.0.1
	- corgilib 4.0.0.4
	- cratedelight 1.2.7
	- create 0.5.1.f
	- create_crush_everything 1.0.2
	- create_sa 2.0.4.
	- creativecore 2.11.24
	- creeperoverhaul 3.0.2
	- ctov 3.4.2
	- curios 5.7.0+1.20.1
	- decorative_blocks 4.0.2
	- deeperdarker 1.2.1
	- despawningeggshatch 4.3
	- difficult_caves 1.0.0
	- disenchanting 2.2.3
	- distractingtrims 2.0.3
	- ditr 1.20.1-1.1.1
	- domesticationinnovation 1.7.1
	- easymagic 8.0.1
	- easyshulkerboxes 8.0.1
	- echochest 8.0.0
	- ecologics 2.2.0
	- elytraslot 6.3.0+1.20.1
	- embeddium 0.3.4+mc1.20.1
	- enchdesc 17.0.13
	- endermanoverhaul 1.0.4
	- endersdelight 1.0.3
	- endrem 5.2.3-R-1.20.1
	- enhancedcelestials 5.0.0.2
	- enlightened_end 5.0.14
	- equipmentcompare 1.3.7
	- everycomp 1.20-2.6.34
	- experienced_crops 1.20.1-1.1.0
	- experienceobelisk 2.0.2-1.20.1
	- explorify 1.3.0-mc1.20
	- extractinator 2.3.0
	- fallingleaves 2.1.0
	- farmersdelight 1.20.1-1.2.4
	- fastback 0.15.2+1.20.1-prerelease
	- fennecfox 1.0.0
	- ferritecore 6.0.1
	- fishermens_trap 2.1.2
	- flywheel 0.6.10-7
	- forge 47.2.17
	- forgottenpots 1.1.4
	- framework 0.6.16
	- galosphere 1.20.1-1.4.1
	- galospheretrimming 1.0.0
	- gardens_of_the_dead 4.0.1
	- geckolib 4.4.2
	- geodes 1.1.1
	- gildedsherds 1.0.2
	- glowberrylantern 1.20.1-2.0
	- goated 1.20-1.3.4
	- goblintraders 1.9.3
	- goodending 1.20.1-1.0.1
	- grassoverhaul 23.06.09
	- habitat 1.3.0
	- hunters_return 1.20.1-11.4.0
	- iceberg 1.1.18
	- idas 1.8.2+1.20.1
	- integrated_api 1.3.7+1.20.1-forge
	- itemborders 1.2.1
	- jei 15.9999
	- jeresources 1.4.0.247
	- kambrik 6.1.1+1.20.1
	- keepsomeinventory 1.3.3
	- kiwi 11.5.3
	- kotlinforforge 4.10.0
	- labels 1.20-1.20
	- letmedespawn 1.2.0
	- libipn 4.0.1
	- lolenderite 2.0.0 - 1.20.1
	- lolgilded 1.3.0 - 1.20.1
	- lolmcv 1.5.0-beta.3
	- lolmcvbmo 1.0.1
	- lolmha 2.0.0 - 1.20.1
	- majruszlibrary 7.0.5
	- majruszsdifficulty 1.9.8
	- map_atlases 1.20-2.7.13
	- mavapi 1.1.3
	- mavm 1.2.4
	- mcwpaintings 1.0.5
	- memoryleakfix 1.1.5
	- metalbundles 8.0.1
	- midnightlib 1.4.2
	- minecraft 1.20.1
	- miners_delight 1.20.1-1.2.3
	- miners_luck 1.0.0
	- mixinextras 0.3.2
	- mixinsquared 0.1.1
	- mobcaptains 3.1.1
	- monster_hunter_villager 1.1.0
	- moonlight 1.20-2.10.1
	- moremobvariants 1.2.2
	- mr_ctov_farmersdelightcompat 2.1
	- mr_logical_dyemixing 1.0.0
	- mysticsbiomes 3.1.6
	- nametagtweaks 3.2
	- ncbetterblastfurnace 1.0.1
	- netherchested 8.0.3
	- netherdepthsupgrade 3.1.3-1.20
	- netherdungeons 1.1.0-alpha2
	- nethers_exoticism 1.2.7
	- nethersdelight 1.20.1-4.0
	- netherskeletons 4.9
	- nocubes_craftable_armor_trims 1.0.0
	- nocubesbetterfletchingtable 1.0.1
	- nocubesbettergrindstone 1.0.1
	- nourished_nether 0.2.5
	- oculus 1.6.15a
	- ohmysherd 1.0.3
	- outer_end 1.0.0
	- overweight_farming 1.20.1-2.1.0-forge
	- patchouli 1.20.1-84-FORGE
	- phantom 20.1.5
	- polymorph 0.49.2+1.20.1
	- pots_and_mimics 1.0.2
	- prism 1.0.5
	- puzzlesaccessapi 8.0.9
	- puzzlesapi 8.1.5
	- puzzleslib 8.1.17
	- quad 1.1.0
	- quark 4.0-436
	- quarkdelight 1.0.0
	- queen_bee 3.1.3
	- radiantgear 2.1.3+1.20.1
	- raised 3.1.1
	- random_crits 1.2.4
	- realmrpg_creep 1.0.2
	- realmrpg_demons 0.9.0
	- realmrpg_skeletons 1.0.3
	- realmrpg_wyrms 1.0.1
	- rei_plugin_compatibilities 12.0.93
	- resourcefulconfig 2.1.2
	- resourcefullib 2.1.23
	- respawninganimals 8.2.0
	- rightclickharvest 3.2.3+1.20.1-forge
	- roughlyenoughitems 12.0.684
	- rubidium 0.7.1
	- salt 1.2.4
	- sawmill 1.20-1.3.4
	- seadwellers 2.9.9
	- secondchanceforge 1.5.1
	- seedbags 1.0.0
	- shieldexp 1.1.7a
	- silverbirch 1.1.1
	- simplecorinthium 1.2.2
	- skeletonhorsespawn 3.8
	- skinlayers3d 1.6.2
	- smartbrainlib 1.13
	- smarterfarmers 1.20-1.8.1
	- snifferplus 0.2.0
	- snowpig 1.20.1-6.0.2
	- spectrelib 0.13.14+1.20.1
	- spelunkers_charm 1.0.0
	- spelunkery 1.20.1-0.3.5
	- spider_caves 20.1.0
	- stalwart_dungeons 1.2.8
	- subterrestrial 2.2.0
	- sullysmod 3.1.2-beta
	- supermartijn642configlib 1.1.8
	- supplementaries 1.20-2.8.1
	- tact 1.0.8
	- taniwha 1.20.0-5.4.4
	- taxfreelevels 1.3.9
	- tempad 2.3.3
	- terrablender 3.0.1.4
	- toolleveling 1.20.1-2.0.0
	- travelerstitles 1.20-Forge-4.0.2
	- trulytreasures 1.20-3.0.0
	- underground_jungle 20.1.0
	- universalbonemeal 8.0.1
	- unusualfishmod 1.0.3
	- verdantvibes 1.0.3-1.20.1
	- villagersellanimals 1.2.1
	- visuality 2.0.2
	- visualworkbench 8.0.0
	- wandering_bags 2.0.7
	- warriorrage 1.0.0
	- wither_drops_netherite_templates 1.0.0
	- xaeroworldmap 1.37.8
	- ydms_redpanda 1.0.4
	- yungsapi 1.20-Forge-4.0.3
	- yungsmenutweaks 1.20.1-Forge-1.0.2
	- zeta 1.0-13
[22Feb2024 12:16:44.033] [main/WARN] [mixin/]: Reference map 'tempad-forge-1.20.1-forge-refmap.json' for tempad.mixins.json could not be read. If this is a development environment you can ignore this message
[22Feb2024 12:16:44.080] [main/WARN] [mixin/]: Reference map 'netherdepthsupgrade.refmap.json' for netherdepthsupgrade.mixins.json could not be read. If this is a development environment you can ignore this message
[22Feb2024 12:16:44.117] [main/WARN] [mixin/]: Reference map 'ditr.refmap.json' for ditr.mixins.json could not be read. If this is a development environment you can ignore this message
[22Feb2024 12:16:44.756] [main/WARN] [mixin/]: Error loading class: net/raphimc/immediatelyfast/feature/map_atlas_generation/MapAtlasTexture (java.lang.ClassNotFoundException: net.raphimc.immediatelyfast.feature.map_atlas_generation.MapAtlasTexture)
[22Feb2024 12:16:45.584] [main/WARN] [mixin/]: Error loading class: twilightforest/TFMagicMapData$TFMapDecoration (java.lang.ClassNotFoundException: twilightforest.TFMagicMapData$TFMapDecoration)
[22Feb2024 12:16:45.766] [main/WARN] [mixin/]: Error loading class: noobanidus/mods/lootr/config/ConfigManager (java.lang.ClassNotFoundException: noobanidus.mods.lootr.config.ConfigManager)
[22Feb2024 12:16:45.826] [main/INFO] [memoryleakfix/]: [MemoryLeakFix] Will be applying 3 memory leak fixes!
[22Feb2024 12:16:45.826] [main/INFO] [memoryleakfix/]: [MemoryLeakFix] Currently enabled memory leak fixes: [targetEntityLeak, biomeTemperatureLeak, hugeScreenshotLeak]
[22Feb2024 12:16:45.884] [main/WARN] [Embeddium/]: Force-disabling mixin 'features.render.world.sky.WorldRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [oculus]) disables it and children
[22Feb2024 12:16:45.885] [main/WARN] [Embeddium/]: Force-disabling mixin 'features.render.world.sky.ClientWorldMixin' as rule 'mixin.features.render.world.sky' (added by mods [oculus]) disables it and children
[22Feb2024 12:16:45.885] [main/WARN] [Embeddium/]: Force-disabling mixin 'features.render.world.sky.BackgroundRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [oculus]) disables it and children
[22Feb2024 12:16:45.886] [main/WARN] [Embeddium/]: Force-disabling mixin 'features.render.gui.font.GlyphRendererMixin' as rule 'mixin.features.render.gui.font' (added by mods [oculus]) disables it and children
[22Feb2024 12:16:45.886] [main/WARN] [Embeddium/]: Force-disabling mixin 'features.render.entity.shadows.EntityRenderDispatcherMixin' as rule 'mixin.features.render.entity' (added by mods [oculus]) disables it and children
[22Feb2024 12:16:45.886] [main/WARN] [Embeddium/]: Force-disabling mixin 'features.render.entity.fast_render.ModelPartMixin' as rule 'mixin.features.render.entity' (added by mods [oculus]) disables it and children
[22Feb2024 12:16:45.887] [main/WARN] [Embeddium/]: Force-disabling mixin 'features.render.entity.fast_render.CuboidMixin' as rule 'mixin.features.render.entity' (added by mods [oculus]) disables it and children
[22Feb2024 12:16:45.887] [main/WARN] [Embeddium/]: Force-disabling mixin 'features.render.entity.cull.EntityRendererMixin' as rule 'mixin.features.render.entity' (added by mods [oculus]) disables it and children
[22Feb2024 12:16:46.082] [main/INFO] [MixinExtras|Service/]: Initializing MixinExtras via ca.fxco.memoryleakfix.mixinextras.service.MixinExtrasServiceImpl(version=0.3.2).
[22Feb2024 12:16:46.618] [main/WARN] [oshi.driver.windows.perfmon.PerfmonDisabled/]: Invalid registry value type detected for PerfOS counters. Should be REG_DWORD. Ignoring: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\PerfOS\Performance\Disable Performance Counters.
[22Feb2024 12:16:47.387] [pool-4-thread-1/INFO] [mixin/]: Instancing error handler class com.illusivesoulworks.polymorph.mixin.IntegratedMixinPlugin
[22Feb2024 12:16:47.387] [pool-4-thread-1/FATAL] [mixin/]: Mixin apply failed quad.mixins.json:ItemEntityMixin -> net.minecraft.world.entity.item.ItemEntity: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on damage could not find any targets matching 'hurt' in net.minecraft.world.entity.item.ItemEntity. Using refmap mixin.refmap.json [PREINJECT Applicator Phase -> quad.mixins.json:ItemEntityMixin -> Prepare Injections ->  -> handler$cke000$damage(Lnet/minecraft/world/damagesource/DamageSource;FLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on damage could not find any targets matching 'hurt' in net.minecraft.world.entity.item.ItemEntity. Using refmap mixin.refmap.json [PREINJECT Applicator Phase -> quad.mixins.json:ItemEntityMixin -> Prepare Injections ->  -> handler$cke000$damage(Lnet/minecraft/world/damagesource/DamageSource;FLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at jdk.internal.reflect.GeneratedConstructorAccessor60.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1311) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1042) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.9.jar:10.0.9+10.0.9+main.dcd20f30]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.minecraftforge.registries.GameData.init(GameData.java:107) ~[forge-1.20.1-47.2.17-universal.jar%23631!/:?]
	at net.minecraftforge.registries.GameData.<clinit>(GameData.java:93) ~[forge-1.20.1-47.2.17-universal.jar%23631!/:?]
	at net.minecraft.core.registries.BuiltInRegistries.forge(BuiltInRegistries.java:429) ~[client-1.20.1-20230612.114412-srg.jar%23626!/:?]
	at net.minecraft.core.registries.BuiltInRegistries.forge(BuiltInRegistries.java:409) ~[client-1.20.1-20230612.114412-srg.jar%23626!/:?]
	at net.minecraft.core.registries.BuiltInRegistries.<clinit>(BuiltInRegistries.java:121) ~[client-1.20.1-20230612.114412-srg.jar%23626!/:?]
	at net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:43) ~[client-1.20.1-20230612.114412-srg.jar%23626!/:?]
	at net.minecraft.client.main.Main.lambda$main$0(Main.java:151) ~[client-1.20.1-20230612.114412-srg.jar%23626!/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]

**Comment by lieonlion** [comment]
It should be fixed with the latest 1.1.1 version

**Comment by lieonlion** [comment]
should be fixed now with 1.1.3 :)) create a new issue if its not
